"""Run the README example briefs and print them as markdown.

    python scripts/run_examples.py > examples_output.md

Needs LLM_* in .env (the refusal example runs without a model). Whatever
this prints is a faithful record of what the agent returned.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.agent import CaptionGenerationError, CaptionRefused, check_brief, generate_caption  # noqa: E402
from app.feed import build_fact_sheet, load_feed  # noqa: E402
from app.llm import LLM, LLMError  # noqa: E402
from main import BRAND_KIT, load_dotenv  # noqa: E402

EXAMPLES = [
    ("A", "Normal generation (week 1)", "data/promotions_feed_week1.json", "Announce this week's new roast."),
    ("B", "Swap test — same brief, week 2 snapshot", "data/promotions_feed_week2.json", "Announce this week's new roast."),
    ("C", "Promo brief while the product is in stock (week 1)", "data/promotions_feed_week1.json",
     "Push the Guatemala Huehuetenango flash sale"),
    ("D", "Edge case — same brief, week 2: product is sold out but still carries a promo code",
     "data/promotions_feed_week2.json", "Push the Guatemala Huehuetenango flash sale"),
]


def main() -> int:
    load_dotenv(Path(".env"))
    brand_kit = BRAND_KIT.read_text(encoding="utf-8")
    try:
        llm = LLM.from_env()
        model = llm.model
    except LLMError as exc:
        llm, model = None, f"(no model configured: {exc})"

    print(f"<!-- generated by scripts/run_examples.py, model: {model} -->\n")
    for label, title, feed_path, brief in EXAMPLES:
        feed = load_feed(feed_path)
        print(f"### Example {label} — {title}\n")
        print(f"```bash\npython main.py --feed {feed_path} --brief \"{brief}\"\n```\n")
        print(f"Feed: `{feed_path}` (snapshot {feed.snapshot_date})\n")
        try:
            check_brief(brief, build_fact_sheet(feed))  # deterministic; runs without a model
            if llm is None:
                raise LLMError("no model configured")
            result = generate_caption(brief, feed, brand_kit, llm)
        except CaptionRefused as exc:
            print("Result: **refused** (exit code 2, no model call made)\n\n```text")
            print(f"Refused: {exc.reason}")
            if exc.alternatives:
                print("Available products in this snapshot: " + ", ".join(exc.alternatives))
            print("```\n")
            continue
        except CaptionGenerationError as exc:
            print(f"Result: **no valid caption** after {len(exc.attempts)} attempts (exit code 1)\n")
            for i, attempt in enumerate(exc.attempts, 1):
                print(f"- attempt {i}: {attempt.caption!r} → " + "; ".join(map(str, attempt.violations)))
            print()
            continue
        except LLMError as exc:
            print(f"Result: **not run** — {exc}\n")
            continue

        print("Result (actual model output, passed validation):\n\n```text")
        print(result.caption)
        print("```\n")
        print(f"Featured: `{', '.join(result.featured_product_ids)}` · attempts: {len(result.attempts)}")
        for i, attempt in enumerate(result.attempts[:-1], 1):
            print(f"- rejected draft {i}: {attempt.caption!r} → " + "; ".join(map(str, attempt.violations)))
        for note in result.notes:
            print(f"- note: {note}")
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
